target_sources_relative(xmoto PRIVATE
  ./AttractMode.cpp ./AttractMode.h
  ./GameState.cpp ./GameState.h
  ./StateCheckWww.cpp ./StateCheckWww.h
  ./StateCreditsMode.cpp ./StateCreditsMode.h
  ./StateDeadJust.cpp ./StateDeadJust.h
  ./StateDeadMenu.cpp ./StateDeadMenu.h
  ./StateEditProfile.cpp ./StateEditProfile.h
  ./StateEditWebConfig.cpp ./StateEditWebConfig.h
  ./StateFinished.cpp ./StateFinished.h
  ./StateHelp.cpp ./StateHelp.h
  ./StateLevelInfoViewer.cpp ./StateLevelInfoViewer.h
  ./StateLevelPackViewer.cpp ./StateLevelPackViewer.h
  ./StateMainMenu.cpp ./StateMainMenu.h
  ./StateManager.cpp ./StateManager.h
  ./StateMenu.cpp ./StateMenu.h
  ./StateMessageBox.cpp ./StateMessageBox.h
  ./StateMessageBoxReceiver.h
  ./StateMultiUpdate.cpp ./StateMultiUpdate.h
  ./StateOptions.cpp ./StateOptions.h
  ./StatePause.cpp ./StatePause.h
  ./StatePlaying.cpp ./StatePlaying.h
  ./StatePlayingLocal.cpp ./StatePlayingLocal.h
  ./StatePlayingNet.cpp ./StatePlayingNet.h
  ./StatePreplaying.cpp ./StatePreplaying.h
  ./StatePreplayingCredits.cpp ./StatePreplayingCredits.h
  ./StatePreplayingGame.cpp ./StatePreplayingGame.h
  ./StatePreplayingNet.cpp ./StatePreplayingNet.h
  ./StatePreplayingReplay.cpp ./StatePreplayingReplay.h
  ./StateReplaying.cpp ./StateReplaying.h
  ./StateRequestKey.cpp ./StateRequestKey.h
  ./StateScene.cpp ./StateScene.h
  ./StateSendReport.cpp ./StateSendReport.h
  ./StateSendVote.cpp ./StateSendVote.h
  ./StateServerConsole.cpp ./StateServerConsole.h
  ./StateSync.cpp ./StateSync.h
  ./StateUpdate.cpp ./StateUpdate.h
  ./StateUpdateDb.cpp ./StateUpdateDb.h
  ./StateUpdateRoomsList.cpp ./StateUpdateRoomsList.h
  ./StateUpdateTheme.cpp ./StateUpdateTheme.h
  ./StateUpdateThemesList.cpp ./StateUpdateThemesList.h
  ./StateUpgradeLevels.cpp ./StateUpgradeLevels.h
  ./StateUploadAllHighscores.cpp ./StateUploadAllHighscores.h
  ./StateUploadHighscore.cpp ./StateUploadHighscore.h
  ./StateViewHighscore.cpp ./StateViewHighscore.h
  ./StateVote.cpp ./StateVote.h
  ./StateWaitServerInstructions.cpp ./StateWaitServerInstructions.h
  ./StateWaiting.cpp ./StateWaiting.h
)
