#!/bin/sh

if ! aclocal $ACLOCAL_FLAGS -I m4
then
    echo "aclocal failed !"                2>&1
    echo "aclocal >= 1.9.6 is required !"  2>&1
    exit 1
fi

if ! automake --gnu --add-missing --copy
then
    echo "automake failed !"               2>&1
    echo "automake >= 1.9.6 is required !" 2>&1
    exit 1
fi

if ! autoconf
then
    echo "autoconf failed !"               2>&1
    echo "autoconf >= 2.13 is required !"  2>&1
    exit 1
fi

echo "You can now run ./configure"

