#!/bin/sh

XMSERVER=localhost
XMPORT=$(basename $0 | sed 's/^xmoto_players_//g')
XMTIMEOUT=3

# wait 3 seconds maximum
plug_getNumberOfXMPlayers() {
    (
	cat <<EOF
20
-1
0
clientsNumberQ
EOF
	) |
    nc -q "$XMTIMEOUT" "$XMSERVER" "$XMPORT" | sed -n "5p"
}

plug_config() {
    cat <<EOF
graph_category games
graph_title X-Moto players (port ${XMPORT})
graph_vlabel players
players.label players
EOF
}

if test "$1" = "config"
then
    plug_config
    exit 0
fi

N=$(plug_getNumberOfXMPlayers)

if ! echo "$N" | grep -qe '^[0-9][0-9]*$'
then
    exit 1
fi

# result
echo "players.value ""$N"
exit 0
