set(CPACK_PACKAGE_NAME "xmoto")
set(CPACK_GENERATOR TGZ)
set(CPACK_SOURCE_GENERATOR STGZ)
set(CPACK_PACKAGE_VERSION_MAJOR 0)
set(CPACK_PACKAGE_VERSION_MINOR 5)
set(CPACK_PACKAGE_VERSION_PATCH 12)
set(CPACK_PACKAGE_FILE_NAME "xmoto-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")

include(cpack/macos.cmake)
