if(LUA_FOUND AND NOT TARGET Lua::Lua)
  add_library(Lua::Lua UNKNOWN IMPORTED)
  set_target_properties(Lua::Lua PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${LUA_INCLUDE_DIR}"
    IMPORTED_LOCATION "${LUA_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${LUA_LIBRARIES}"
    VERSION "${LUA_VERSION_STRING}"
  )
endif()

