if(SDL_FOUND AND NOT TARGET SDL::SDL)
  add_library(SDL::SDL INTERFACE IMPORTED)
  set_target_properties(SDL::SDL PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL_INCLUDE_DIR}"
    INTERFACE_LINK_LIBRARIES "${SDL_LIBRARY}"
    # VERSION "${SDL_VERSION_STRING}"
  )
endif()

if(SDL_GFX_FOUND AND NOT TARGET SDL::SDL_gfx)
  add_library(SDL::SDL_gfx UNKNOWN IMPORTED)
  set_target_properties(SDL::SDL_gfx PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL_GFX_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${SDL_GFX_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${SDL_GFX_LIBRARIES}"
    VERSION "${SDL_GFX_VERSION_STRING}"
  )
endif()

if(SDL_MIXER_FOUND AND NOT TARGET SDL::SDL_mixer)
  add_library(SDL::SDL_mixer UNKNOWN IMPORTED)
  set_target_properties(SDL::SDL_mixer PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL_MIXER_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${SDL_MIXER_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${SDL_MIXER_LIBRARIES}"
    VERSION "${SDL_MIXER_VERSION_STRING}"
  )
endif()

if(SDL_NET_FOUND AND NOT TARGET SDL::SDL_net)
  add_library(SDL::SDL_net UNKNOWN IMPORTED)
  set_target_properties(SDL::SDL_net PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL_NET_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${SDL_NET_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${SDL_NET_LIBRARIES}"
    VERSION "${SDL_NET_VERSION_STRING}"
  )
endif()

if(SDL_SOUND_FOUND AND NOT TARGET SDL::SDL_sound)
  add_library(SDL::SDL_sound UNKNOWN IMPORTED)
  set_target_properties(SDL::SDL_sound PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL_SOUND_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${SDL_SOUND_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${SDL_SOUND_LIBRARIES}"
    VERSION "${SDL_SOUND_VERSION_STRING}"
  )
endif()

if(SDL_TTF_FOUND AND NOT TARGET SDL::SDL_ttf)
  add_library(SDL::SDL_ttf UNKNOWN IMPORTED)
  set_target_properties(SDL::SDL_ttf PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${SDL_TTF_INCLUDE_DIRS}"
    IMPORTED_LOCATION "${SDL_TTF_LIBRARY}"
    INTERFACE_LINK_LIBRARIES "${SDL_TTF_LIBRARIES}"
    VERSION "${SDL_TTF_VERSION_STRING}"
  )
endif()
